# Generated by Django 2.2.2 on 2020-01-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='face_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNum', models.IntegerField()),
                ('faceImg', models.ImageField(upload_to='face_img')),
            ],
        ),
        migrations.CreateModel(
            name='predict_age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realAge', models.IntegerField()),
                ('predictAge', models.IntegerField()),
            ],
        ),
    ]
