# Generated by Django 3.0 on 2020-02-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realAge', models.IntegerField()),
                ('faceImg', models.ImageField(upload_to='face_img')),
            ],
        ),
        migrations.CreateModel(
            name='Predict_age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realAge', models.IntegerField()),
                ('predictAge', models.IntegerField()),
                ('diff', models.IntegerField(default=0)),
                ('gender', models.CharField(default='m', max_length=10)),
            ],
        ),
    ]
