# Generated by Django 2.2.2 on 2020-01-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOAY', '0002_face_img_realage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face_img',
            name='realAge',
            field=models.CharField(max_length=10),
        ),
    ]
