# Generated by Django 2.2.2 on 2020-01-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOAY', '0003_auto_20200106_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face_img',
            name='idNum',
        ),
        migrations.AddField(
            model_name='face_img',
            name='fileName',
            field=models.CharField(default='', max_length=255),
        ),
    ]
