# Generated by Django 2.2.2 on 2020-01-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOAY', '0004_auto_20200106_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict_age',
            name='diff',
            field=models.IntegerField(default=0),
        ),
    ]
