# Generated by Django 2.2.2 on 2020-01-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOAY', '0005_predict_age_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict_age',
            name='gender',
            field=models.CharField(default='m', max_length=10),
        ),
    ]
