# Generated by Django 2.2.2 on 2020-01-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOAY', '0006_predict_age_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face_img',
            name='fileName',
        ),
        migrations.AlterField(
            model_name='face_img',
            name='realAge',
            field=models.IntegerField(default=20),
        ),
    ]
