# Generated by Django 2.2.2 on 2020-01-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOAY', '0007_auto_20200111_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face_img',
            name='realAge',
            field=models.IntegerField(),
        ),
    ]
