# Generated by Django 3.0 on 2020-02-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nCov', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='thumbImg',
            field=models.ImageField(null=True, upload_to='thumb_Img'),
        ),
        migrations.AlterModelTable(
            name='board',
            table='community_fact',
        ),
    ]
