# Generated by Django 3.0 on 2020-02-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nCov', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='contents',
            field=models.CharField(max_length=30, verbose_name='팩트체크'),
        ),
    ]
