# Generated by Django 3.0 on 2020-02-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nCov', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='tag',
            field=models.ManyToManyField(to='nCov.Tag', verbose_name='태그'),
        ),
    ]
