# Generated by Django 3.0 on 2020-02-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nCov', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '게시물', 'verbose_name_plural': '게시물'},
        ),
        migrations.AlterModelTable(
            name='tag',
            table='community_board',
        ),
    ]
