# Generated by Django 3.0 on 2020-02-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nCov', '0002_auto_20200221_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='link',
            field=models.CharField(max_length=300, verbose_name='링크'),
        ),
    ]
