# Generated by Django 2.2.2 on 2020-02-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nCov', '0002_auto_20200202_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pubDate',
            field=models.CharField(max_length=255),
        ),
    ]
