# Generated by Django 3.0 on 2020-02-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nCov', '0002_auto_20200223_1253'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table=None,
        ),
    ]
